Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
turtle.goto(50, 0)
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    turtle.goto(50, 0)
NameError: name 'turtle' is not defined. Did you mean: 'tuple'?
import turtle
turtle.goto(50, 0)
turtle.right(135)
turtle.goto(50, 0)
turtle.forward(50)
turtle,goto(70,20)
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    turtle,goto(70,20)
NameError: name 'goto' is not defined
tultle.penup()
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    tultle.penup()
NameError: name 'tultle' is not defined. Did you mean: 'turtle'?
turtle.penup()
turtle.left(180)
turtle.forward(80)
turtle.right(135)
turtle.pendown()
turtle.forward(80)
turtle.left(180)
turtle.forward(40)
turtle.right(90)
turtle.forward(25)
turtle.penup()
turtle.left(180)
KeyboardInterrupt
turtle.left(180)
turtle.right(135)
turtle.forward(100)
turtle.circle(30)
turtle.pendown()
turtle.circle(30)
turtle.left(180)
turtle.penup()
turtle.forward(100)
turtle.forward(40)
turtle.right(45)
turtle.forward(20)
turtle.pendown()
turtle.circle(30)
turtle.undo
<function undo at 0x000001FB43FFF910>
turtle.updo
Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    turtle.updo
AttributeError: module 'turtle' has no attribute 'updo'. Did you mean: 'undo'?
turtle.undo()
turtle.penup()
turtle.right(90)
turtle.forward(20)
turtle.forward(10)
turtle.forward(10)
turtle.penup()
turtle.pendown()
turtle.circle(30)
turtle.undo()
turtle.left(180)
turtle.circle(30)
turtle.undo()
turtle.right(90)
turtle.circle(30)
turtle.right(90)
turtle.penup()
turtle.forward(20)
turtle.forward(10)
turtle.right(90)
turtle.forward(40)
turtle.left(180)
turtle.pendown()
turtle.forward(80)
turtle.forward(20)
turtle.penup()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.pendown()
turtle.forward(40)
turtle.left(90)
turtle.forward(60)
turtle.penup()
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.undo()
turtle.forward(160)
turtle.right(30)
KeyboardInterrupt
turtle.right(90)
turtle.right(90)
turtle.pendown()
turtle.forward(50)
turtle.left(150)
turtle.left(60)
turtle.penup()
turtle.forward(50)
turtle.forward(10)
turtle.left(180)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.forward(10)
turtle.circle(30)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.left(180)
turtle.forward(80)
turtle.undo()
turtle.forward(50)
turtle.pendown()
turtle.forward(20)
turtle.left(90)
turtle.forward(50)
turtle.left(180)
turtle.forward(100)
turtle.forward(20)
turtle.left(180)
turtle.forward(40)
turtle.left(90)
turtle.forward(20)
turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(40)
turtle.left(180)
turtle.pendown()
turtle.forward(50)
turtle.forward(10)
turtle.right(90)
turtle.forward(50)
